version: "3"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senhafacil
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      - app-network

  redis:
    image: "redis:latest"
    ports:
      - "6378:6379"
    volumes:
      - "redis:/var/lib/redis/data"
    networks:
      - app-network

  desafio-sre:
    build: "~/elven/estudos/desafio-sre/docker/Dockerfile"
    volumes:
      - ".:/app"
    ports:
      - "5000:5000"
      - "9999:9999"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senhafacil
      POSTGRES_DB: postgres
    depends_on:
      - redis
      - postgres
    networks:
      - app-network

volumes:
  postgres: {}
  redis: {}

networks:
  app-network:
    driver: bridge
