apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: desafio-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lumr/desafio-ps-sre.git
    path: k8s
    targetRevision: HEAD
    directory: {}
    destination:
      #server: https://192.168.1.100:8443
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated: {}
    syncOptions:
      - CreateNamespace=true