apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    
spec:
  tls:
    - hosts:
        - desafio.app
      secretName: desafio-app-tls
  rules:
    - host: desafio.app
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: svc-app
              port:
                number: 80
        - path: /postgres
          pathType: Exact
          backend:
            service:
              name: svc-app
              port:
                number: 80
        - path: /redis
          pathType: Exact
          backend:
            service:
              name: svc-app
              port:
                number: 80
        - path: /error
          pathType: Exact
          backend:
            service:
              name: svc-app
              port:
                number: 80
        - path: /metrics
          pathType: Exact
          backend:
            service:
              name: svc-app
              port:
                number: 9999
