#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: configmap-app
#data:
#  REDIS_HOST: "svc-redis"
#  REDIS_PORT: "6379"
#  POSTGRES_HOST: "svc-postgres"
#  POSTGRES_PORT: "5432"
#  POSTGRES_USER: "postgres"
#  POSTGRES_DB: "postgres"
