apiVersion: v1
kind: Service
metadata:
  name: svc-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      name: web
    - port: 9999
      targetPort: 9999
      name: metrics
  selector:
    app: app-desafio-sre
