apiVersion: v1
kind: Service
metadata:
  name: svc-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres-port
      name: postgres
  selector:
    app: postgres-desafio-sre
