name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Config credenciais DockerHub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      
      - name: Build and push image
        uses: docker/build-push-action@v5                                      # Usa a ação oficial do Docker para build e push
        with :
          context: .                                                           # Usa o diretório atual como contexto do build
          push: true                                                           # Habilita o push da imagem após o build
          tags: |                                                              # Define as tags para a imagem
            ${{ secrets.DOCKER_HUB_USERNAME }}/desafio-sre:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/desafio-sre:${{ github.sha }}
           
          # Desabilita a adição automática de tags baseadas no ref
          tags-from-ref: false
      
      - name: Setup git
        run: |
          # Configura as credenciais do git
          git config --global user.email "lucasmenezes9251@gmail.com"
          git config --global user.name "Lucas de Menezes Rodrigues"
          git config --global --add safe.directory /github/workspace
        
      - name: Update deployment file
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: |
          # Configura a URL do repo
          git remote set-url origin https://x-access-token:${TOKEN_GITHUB}@github.com/lumr/desafio-ps-sre.git
          
          # Atualiza arquivo de deployment com a nova tag
          sed -i "s|image:.*|image: lumr/app-desafio-sre:${{ github.sha }}|" k8s/deployment/deploy-app.yaml
          
          # adiciona as mudanças
          git add k8s/deployment/deploy-app.yaml
          
          # commit as mudanças
          git commit -m "Update deployment file para ${{ github.sha }}"
          
          # push as mudanças
          git push origin main

      # Tags latest e da versão específica
      
      #- name: Config credenciais AWS
      #  uses: aws-actions/configure-aws-credentials@v4
      #  with:
      #    role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      #    aws-region: ${{ secrets.AWS_REGION }}
      
      #- name: Login no ECR
      #  id: login-ecr
      #  uses: aws-actions/amazon-ecr-login@v2

      #- name: Build, tag, and push image para o ECR
      #  env:
      #    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry}}
      #    ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_DESAFIO_SRE}}
      #    IMAGE_TAG: ${{ github.sha}}
      #  run: |
      #    # Build da imagem
      #    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      #    # Push da imagem
      #    docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
